### ISSUE TITLE
Details about how to generate effectivate grasp data.

### ISSUE THREAD

**Issue by CodingCatMountain** [qianbot/FFHNet#3]
@qqianfeng Hi. In the open issue #2 , you mentioned how to convert the object point clouds into bps format. That is very useful. However, I believe how to generate the robotics dexterous hand grasping gestures is more important. So could you introduce the procedure of generating robotics dexterous hand grasping gestures? Did you used some grasping framework, e.g., GraspIt? Looking forward to your reply! :)

**Comment by qqianfeng** [comment]
Hi @CodingCatMountain ,very good point. So the grasping gestures can be generated by graspit, but the poses from graspit can be not human-like, and have larger sim2real gap. We proposed a heuristic method to generate grasping gestures based on point cloud normals. More details you can refer to paper FFHNet, Section IV. GRASP DATA GENERATION. Btw the code for this is also public [here](https://github.com/qqianfeng/grasp-pipeline/blob/master/src/grasp_pipeline/server/get_preshape_for_all_points_server.py).

**Comment by CodingCatMountain** [comment]
@qqianfeng Thanks for sharing this repo. I will close this issue.
